version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Adminpass@123ß
      MYSQL_DATABASE: studentrecorddb
      MYSQL_USER: phpuser
      MYSQL_PASSWORD: Password
    volumes:
      - "db_data:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

volumes:
  db_data: